export interface AccessLog {
  id: string;
  domain_id: string | null;
  ip: string;
  ip_type?: string;
  user_agent: string;
  headers?: any;
  country: string;
  country_source?: string;
  asn?: string | null;
  isp?: string | null;
  is_datacenter?: boolean;
  is_proxy?: boolean;
  is_vpn?: boolean;
  is_safe: boolean;
  param_received: string;
  detection_results?: any;
  detection_layers?: any;
  platform_type?: string;
  platform_confidence?: number;
  platform_reasoning?: string;
  accept_language?: string | null;
  referer_url?: string | null;
  ad_network?: string;
  gclid_present?: boolean;
  gclid_valid?: boolean;
  gclid_length?: number;
  gclid_entropy?: number;
  gclid_reused?: boolean;
  utm_params?: any;
  risk_score_breakdown?: any;
  final_risk_score?: number;
  decision_gate?: string;
  primary_reason?: string;
  secondary_reasons?: string[];
  overrides_applied?: string[];
  edge_version?: string;
  detection_pipeline_version?: string;
  php_template_version?: string;
  request_id?: string;
  processing_time_ms?: number;
  fatal_error?: boolean;
  fatal_error_stage?: string | null;
  created_at: string;
}
