/*
  # Add bypass parameter field to protected domains

  1. Changes
    - Add `bypass_param` column to `protected_domains` table
      - This is a unique parameter that will be added to URLs when all security layers pass
      - Each domain has its own unique bypass parameter
      - This parameter is generated by the system and stored in IceWall only
      - The PHP code does not contain this parameter - it's added dynamically after validation

  2. Security
    - The bypass_param is unique per domain
    - It's generated as a short, URL-safe string
    - Only IceWall knows the bypass parameter for each domain
*/

-- Add bypass_param column if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'protected_domains' AND column_name = 'bypass_param'
  ) THEN
    ALTER TABLE protected_domains ADD COLUMN bypass_param text;
  END IF;
END $$;

-- Generate bypass params for existing domains that don't have one
UPDATE protected_domains
SET bypass_param = '_bp' || substr(md5(random()::text), 1, 8)
WHERE bypass_param IS NULL;

-- Add unique constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'protected_domains_bypass_param_key'
  ) THEN
    ALTER TABLE protected_domains ADD CONSTRAINT protected_domains_bypass_param_key UNIQUE (bypass_param);
  END IF;
END $$;